# Generated by Django 4.0.6 on 2022-08-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('relacion', models.CharField(max_length=20)),
                ('cumpleaños', models.DateField()),
            ],
        ),
    ]
